version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  colored:
    class: colorlog.ColoredFormatter
    format: "%(log_color)s[%(asctime)s] [%(levelname)-7s] - %(name)s - (%(filename)s:%(lineno)s) %(message)s "
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: colored
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [console]