version: 1
client_id: ''
client_secret: ''
keycloack_host: 'https://centralidp.beta.demo.catena-x.net'
keycloack_realm: '/auth/realms/CX-Central/protocol/openid-connect/token'
registry_url: 'https://semantics.beta.demo.catena-x.net/registry'
twins_pickle_pre_name: 'twins'
token_pickle: 'token.pickle'
bpn: 
 - {'company':'ZF', 'name': 'Tier A','value':'BPNL0000000005VV'}
 - {'company':'BMW', 'name': 'OEM A','value':'BPNL0000000004WK'}
 - {'company':'Benz', 'name': 'OEM B','value':'BPNL0000000002XY'}
 - {'company':'BOSCH', 'name': 'Tier B','value':'BPNL0000000006V6'}
 - {'company':'BASF', 'name': 'N-Tier A','value':'BPNL0000000003X9'}
 - {'company':'CCT', 'name': 'Sub Tier B','value':'BPNL0000000008TS'}
 - {'company':'GRIES', 'name': 'Tier C','value':'BPNL0000000007UH'}
force_reload: True
check_output_filename: 'DTRCheck'