version: 1
client_id: 'sa-cl6-cx-9'
client_secret: 'yeuF9syHZdgc247I517ydjYQw5fD8PJh'
keycloack_host: 'https://centralidp.int.demo.catena-x.net'
keycloack_realm: '/auth/realms/CX-Central/protocol/openid-connect/token'
registry_url: 'https://semantics.int.demo.catena-x.net'
twins_pickle_pre_name: 'twins'
token_pickle: 'token.pickle'
force_reload: True
semanticIds: 
- 'urn:bamm:io.catenax.serial_part_typization:1.1.0#SerialPartTypization'
- 'urn:bamm:io.catenax.assembly_part_relationship:1.1.0#AssemblyPartRelationship'
- 'urn:bamm:io.catenax.material_for_recycling:1.1.0#MaterialForRecycling'
- 'urn:bamm:io.catenax.certificate_of_destruction:1.0.0#CertificateOfDestruction'
- 'urn:bamm:io.catenax.vehicle.product_description:1.0.1#ProductDescription'
- 'urn:bamm:io.catenax.battery.product_description:1.0.1#ProductDescription'
- 'urn:bamm:io.catenax.return_request:1.0.0#ReturnRequest'
- 'urn:bamm:io.catenax.physical_dimension:1.0.0#PhysicalDimension'
- 'urn:bamm:io.catenax.batch:1.0.0#Batch'
check_output_filename: 'DTRCheck'
