version: 1
client_id: s34                         # keycloack client id 
client_secret: aöklsdjföalksdjfölkasdj # keycloack secret
keycloack_host: https://centralidp.int.demo.catena-x.net # keycloack host
keycloack_realm: /auth/realms/CX-Central/protocol/openid-connect/token # keycloack realm
registry_url: https://semantics.int.demo.catena-x.net # URL of registry service
force_reload: True                     # True force programm to reload twins from registry and not use cache
semanticIds:                           # list of semanticId's to be checked
- semanticId: djasdfj
  linkedSpecificAssetIds:
    - specificAssetId: manufacturerId
      checkLevel: mandatory 
    - specificAssetId: manufacturerPartId
      checkLevel: optional
check_output_filename: DTRCheck       # output filename, this will be appended with 
                                      # date time and environment information
bpn:                                  # optional: list of specific bpn values which are beeing tested.
                                      # If config is missing whole registry entries will be checked
  - company: A
    name: Tier A
    value: BPNL0000000XXXXX
proxies:                              # proxy settings for get requests
  http: 
  https: 
edc_catalog_check: True               # Should an EDC Catalog check of each participant in the Network be done
edc_consumer_control_plane:           # EDC consumer control plane url from which the catalog shall be retrieved