version: 1
client_id: ''
client_secret: ''
keycloack_host: 'https://centralidp.int.demo.catena-x.net'
keycloack_realm: '/auth/realms/CX-Central/protocol/openid-connect/token'
registry_url: 'https://semantics.int.demo.catena-x.net'
twins_pickle_pre_name: 'twins'
token_pickle: 'token.pickle'
force_reload: True
semanticIds: 
- 'urn:bamm:io.catenax.serial_part_typization:1.1.0#SerialPartTypization'
- 'urn:bamm:io.catenax.assembly_part_relationship:1.1.0#AssemblyPartRelationship'
- 'urn:bamm:io.catenax.material_for_recycling:1.1.0#MaterialForRecycling'
- 'urn:bamm:io.catenax.certificate_of_destruction:1.0.0#CertificateOfDestruction'
- 'urn:bamm:io.catenax.vehicle.product_description:1.0.1#ProductDescription'
- 'urn:bamm:io.catenax.battery.product_description:1.0.1#ProductDescription'
- 'urn:bamm:io.catenax.return_request:1.0.0#ReturnRequest'
- 'urn:bamm:io.catenax.physical_dimension:1.0.0#PhysicalDimension'
- 'urn:bamm:io.catenax.batch:1.0.0#Batch'
check_output_filename: 'DTRCheck'
bpn: 
#  - {'company':'ZF', 'name': 'Tier A','value':'BPNL00000003B2OM'}
#  - {'company':'ZF', 'name': 'Sub Tier A','value':'BPNL00000003B3NX'}
#  - {'company':'BMW', 'name': 'OEM A','value':'BPNL00000003AYRE'}
#  - {'company':'Benz', 'name': 'OEM B','value':'BPNL00000003AVTH'}
#  - {'company':'SAP', 'name': 'OEM C','value':'BPNL00000003AZQP'}
#  - {'company':'BOSCH', 'name': 'Tier B','value':'BPNL00000003B5MJ'}
#  - {'company':'BASF', 'name': 'N-Tier A','value':'BPNL00000003B0Q0'}
#  - {'company':'HENKEL', 'name': 'Sub Tier B','value':'BPNL00000003AXS3'}
#  - {'company':'GEC', 'name': 'Tier C','value':'BPNL00000003CSGV'}
#  - {'company':'Siemens', 'name': 'Sub Tier C','value':'BPNL00000000BJTL'}
proxies: { 'http':'', 'https':''}